[package]
name = "gw_concurrency"
version = "0.1.0"
edition = "2021"

[lib]
name = "opcode"

[[bin]]
name = "opcs"
path = "src/bin/server.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
